export const TESTIMONIALS = [
    {
        name: "Roshan Kumar Kanu",
        comment: "Sometimes finding a reliable dental is more difficult than actually going through the procedure. I felt the same before I ever came up with Om Kapan Dental clinic. Om Kapan Dental freed me from this hassle of looking for the best dental in kapan and in Kathmandu. It has been my first choice after I've done my first treatment. Highly recommended to everyone who want to have dental checkup or looking for a reliable dental in kapan.",
        img: "/images/testimonials/t1.webp",
        star: 4,
    },
    {
        name: "Prativa Pandey",
        comment: "I had my cleanings and regular dental checkup done here. The ambience was really great and the staffs were very cooperative. The doctor is experienced and really knows things. He was so good with communication and took care of all my concerns. Highly recommend for your comprehensive dental care.",
        img: "/images/testimonials/t2.webp",
        star: 5,
    },
    {
        name: "mausham lamichhane",
        comment: "I usually feel nervous about visiting the dentist, but the team here made me feel relaxed from the moment I arrived. The dentist is professional and patient. The treatment was painless, and everything was explained in detail. Thank you for making my visit such a pleasant experience.",
        img: "/images/testimonials/t3.webp",
        star: 4,
    },
    {
        name: "Parmarth Paudel",
        comment: "I had a comforting experience here. Whenever you go to any clinic the apprehension about pain, procedure and expenses is overwhelming. The environment there allowed me to calmly continue my treatment. The dentists are so amazing and friendly. Thankfully now my oral health is in good condition. 😃 …",
        img: "/images/testimonials/t4.webp",
        star: 5,
    },
    {
        name: "Pratikchya Kshe",
        comment: "I did my daughter’s treatment there we are happy with their services. Dr Bibek is vey nice and he is passionate about his job. He is friendly to children, handles them well.",
        img: "/images/testimonials/t5.webp",
        star: 5,
    },
    {
        name: "Parmeshwor Dharel",
        comment: "Very professional dental service with a clean and comfortable environment. The doctors were friendly, explained the treatment clearly, and made me feel at ease throughout the visit. Highly satisfied with the care.",
        img: "/images/testimonials/t6.webp",
        star: 5,
    },
    {
        name: "Anjali Chaudhary",
        comment: "Fantastic service friendly doctor's and specially thanks to dr.sandhya and Mrs.Ganga 💗 …",
        img: "/images/testimonials/t7.webp",
        star: 5,
    },
    {
        name: "Anish Shrestha",
        comment: "best dental in kathmandu from my experience",
        img: "/images/testimonials/t8.webp",
        star: 5,
    },
    {
        name: "Suraj Khadka",
        comment: "Best place for dental treatment.",
        img: "/images/testimonials/t9.webp",
        star: 5,
    },
    {
        name: "Neebi Shrestha",
        comment: "Great experience friendly staff, excellent care and a very comfortable environment highly recommended🙏😊 …",
        img: "/images/testimonials/t10.webp",
        star: 5,
    },
    {
        name: "Ankita Chaudhary",
        comment: "Very effective communication and ethical dental  practice . Entire team is so compassionate and knowledgeable .Best experience I have ever had😊 Highly recommended. …",
        img: "/images/testimonials/t11.webp",
        star: 5,
    },
    {
        name: "bandej khadka",
        comment: "Very professional care . Thank you 🙏 …",
        img: "/images/testimonials/t12.webp",
        star: 5,
    },
    {
        name: "Rupak Dhakal",
        comment: "Excellent service. 💯 …",
        img: "/images/testimonials/t13.webp",
        star: 5,
    },
    {
        name: "Anil Pokhrel",
        comment: "Best dental clinic",
        img: "/images/testimonials/t14.webp",
        star: 5,
    },
    {
        name: "Notreallybihan41",
        comment: "Best facilities with the best available doctors in kathmandu. Highly recommend",
        img: "/images/testimonials/t15.webp",
        star: 5,
    },
    {
        name: "ashok ayer",
        comment: `Excellent experience at Om Kapan Dental Clinic. The clinic is exceptionally clean, well-maintained, and equipped with modern dental technology.`,
        img: "/images/testimonials/t16.webp",
        star: 5,
    },
];